" GVIM
" set guifont=Menlo:h10   
" set guifont=Hack\ 10   
set guifont=Hack\ 12
set guioptions-=m  "menu bar 
" is sometimes uselful for LaTeX -> put it in filetype
set guioptions-=T  "toolbar
set guioptions-=r  "right scrollbar
set guioptions-=L  "left scrollbar


